dist: xenial

language: c

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - libtool
      - intltool
      - libglib2.0-dev
      - libgtk-3-dev
      - libgcrypt20-dev
      - nettle-dev
      - libb2-dev
      - libmbedtls-dev
      - linux-libc-dev
      - librsvg2-bin
      - libxml2-utils
      - at-spi2-core
      - xvfb
      - gnome-icon-theme
      - libnautilus-extension-dev
      - libnemo-extension-dev

env:
  - WITH_GTK=3.0

script:
  - ./autogen.sh
  - export DISTCHECK_CONFIGURE_FLAGS=$(echo
      --with-gtk=${WITH_GTK}
      --enable-debug
      --enable-blake2
      --enable-gcrypt
      --enable-glib-checksums
      --enable-mbedtls
      --enable-nettle
      --enable-linux-crypto
      --enable-nautilus
      --enable-nemo
      --disable-dependency-tracking
      )
  - CFLAGS="--coverage" ./configure ${DISTCHECK_CONFIGURE_FLAGS}
  - make -j$(nproc) VERBOSE=1 check
  - make -j$(nproc) VERBOSE=1 DESTDIR=$(mktemp -d) distcheck

after_success:
  - bash <(curl -s https://codecov.io/bash)
